Entry.create!(name: 'Matz')
Entry.create!(name: 'DHH')
Entry.create!(name: 'Jose Vadim')
Entry.create!(name: 'Avdi Grim')
Entry.create!(name: 'Steve Klabnik')
Entry.create!(name: 'Aaron Patterson')
Entry.create!(name: 'Kremez Dmitry')
Entry.create!(name: 'Krulov Sergey')